In [1]:
import numpy as np

In [22]:
mylist=[1,2,3,4,5,6,7,8]
lis=[12,13,14,16,17,11,19,18]
arr=np.array(mylist,dtype=int)
arr5=np.array(lis)
arr2=np.array([mylist,lis])
arr3=np.array(mylist+lis)

In [17]:
print(arr)
print(type(mylist))
print(type(arr))
print(mylist)
print(arr2,arr3)

[1 2 3 4 5 6 7 8]
<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8]
[[ 1  2  3  4  5  6  7  8]
 [12 13 14 16 17 11 19 18]] [ 1  2  3  4  5  6  7  8 12 13 14 16 17 11 19 18]


In [18]:
print(arr.ndim)
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

1
(8,)
(2, 8)
(16,)


In [21]:
arr1=arr.reshape(4,2)
arr4=arr2.reshape(8,2)
print(arr1)
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [12 13]
 [14 16]
 [17 11]
 [19 18]]


In [29]:
print(np.add(arr,arr5))
print(np.subtract(arr,arr5))
print(np.multiply(arr,arr5))
print(np.dot(arr,arr5))
print(np.divide(arr,arr5))
print(np.sum(arr5))

[13 15 17 20 22 17 26 26]
[-11 -11 -11 -12 -12  -5 -12 -10]
[ 12  26  42  64  85  66 133 144]
572
[0.08333333 0.15384615 0.21428571 0.25       0.29411765 0.54545455
 0.36842105 0.44444444]
120


In [33]:
print(np.mean(arr))
print(np.std(arr5))
print(np.median(arr2))
print(np.max(arr5))

4.5
2.7386127875258306
9.5
19


In [40]:
ran=np.random.randint(1, 101, 10)
print(ran)
np.random.seed(42)
print(np.random.rand(3))

[ 83  87  75  75  88 100  24   3  22  53]
[0.37454012 0.95071431 0.73199394]


In [42]:
print(arr[arr > 4])
print(arr[arr % 2 == 0])
arr[arr < 5] = 0
print(arr)

[5 6 7 8]
[2 4 6 8]
[0 0 0 0 5 6 7 8]


Student Marks Analytics System
🎯 Goal:
Work only with NumPy arrays.
import numpy as np
marks = np.array([
    [85, 78, 92],
    [70, 88, 90],
    [60, 75, 85],
    [95, 92, 98]
])
Tasks:
Calculate student-wise average
Subject-wise average
Highest scorer
Rank students using total marks
Normalize marks between 0 and 1
Add bonus marks only if average < 80

In [10]:
import numpy as np
marks = np.array([
    [85, 78, 92],
    [70, 88, 90],
    [60, 75, 85],
    [95, 92, 98]
])
stu_avg = np.mean(marks, axis=1)
print(stu_avg)
sub_avg=np.mean(marks,axis=0)
print(sub_avg)
print(max(stu_avg))

[85.         82.66666667 73.33333333 95.        ]
[77.5  83.25 91.25]
95.0


In [20]:
stu_sum=np.sum(marks,axis=1)
top_student = np.argmax(stu_sum)
print(top_student+1," is the highest scorer")

4  is the highest scorer


In [21]:
rank=np.argsort(stu_sum)[::-1]
print(rank)

[3 0 1 2]


In [22]:
min_val = np.min(marks)
max_val = np.max(marks)
normalized = (marks - min_val) / (max_val - min_val)
print(normalized)

[[0.65789474 0.47368421 0.84210526]
 [0.26315789 0.73684211 0.78947368]
 [0.         0.39473684 0.65789474]
 [0.92105263 0.84210526 1.        ]]


Sales Data Analyzer
sales = np.array([
    [200, 250, 300],
    [150, 180, 210],
    [400, 420, 390],
    [100, 130, 160]
])

Each row = Store
Each column = Month

Tasks:
Total sales per store
Best performing month
Store with highest growth
Percentage increase month-wise
Standard deviation per store

In [25]:
sales = np.array([
    [200, 250, 300],
    [150, 180, 210],
    [400, 420, 390],
    [100, 130, 160]
])
t_s=np.sum(sales,axis=1)
print(t_s)

[ 750  540 1210  390]


In [31]:
t_m=np.sum(sales,axis=0)
b_m=np.argmax(t_m)
print(t_m)
print("best performing month:",b_m+1)

[ 850  980 1060]
best performing month: 3


In [38]:
growth=sales[:,-1]-sales[:,0]
print(growth)
h_g=np.argmax(growth)
print(h_g+1)

[100  60 -10  60]
1


In [41]:
perc_1_2 = ((sales[:,1] - sales[:,0]) / sales[:,0]) * 100
print(perc_1_2)
perc_2_3 = ((sales[:,2] - sales[:,1]) / sales[:,1]) * 100
print(perc_2_3)

[25. 20.  5. 30.]
[20.         16.66666667 -7.14285714 23.07692308]


In [42]:
std_dev = np.std(sales, axis=1)
print(std_dev)

[40.82482905 24.49489743 12.47219129 24.49489743]


Random Matrix Challenge
Create 5×5 matrix (1–100)
Find:
Row-wise max
Column-wise min
Diagonal sum
Sort each row
Replace even numbers with 0
Extract values > mean

In [44]:
ranmat=np.random.randint(1,100,(5,5))
print(ranmat)

[[66 98 47 64 63]
 [59 88 53 85 33]
 [93 78  7 51 18]
 [65 92 56 97 76]
 [92  8 74 97 94]]


In [45]:
row_max=np.max(ranmat,axis=1)
print(row_max)

[98 88 93 97 97]


In [53]:
col_min=np.min(ranmat,axis=0)
print(col_min)

[59  8  7 51 18]


In [104]:
ran_sort=np.sort(ranmat,axis=1)
print(ran_sort)

[[47 63 64 66 98]
 [33 53 59 85 88]
 [ 7 18 51 78 93]
 [56 65 76 92 97]
 [ 8 74 92 94 97]]


In [56]:
sum=np.sum(np.diag(ranmat))
print(sum)

352


In [57]:
ranma=ranmat.copy()
ranma[ranma%2==0]=0
print(ranma)

[[ 0  0 47  0 63]
 [59  0 53 85 33]
 [93  0  7 51  0]
 [65  0  0 97  0]
 [ 0  0  0 97  0]]


In [61]:
mean=np.mean(ranmat)
greater_than_mean = ranmat[ranmat > mean]
print(greater_than_mean)

[98 88 85 93 78 92 97 76 92 74 97 94]


Broadcasting & Masking Master Challenge
Create random 4×4 matrix
Add different values to each row
Multiply each column by different number
Create mask for values > 50
Count how many values satisfy condition

In [63]:
mat=np.random.randint(1,100,(4,4))
print(mat)

[[21 91  9 57]
 [97 37 65 26]
 [83  5 37 59]
 [83  4 29 57]]


In [67]:
add_value=np.array([5,10,15,20]).reshape(4,1)
mat1=mat+add_value
print(mat1)

[[26 96 14 62]
 [55 55 55 55]
 [60 60 60 60]
 [65 65 65 65]]


In [68]:
mat2=mat*add_value
print(mat2)

[[105 455  45 285]
 [450 450 450 450]
 [675 675 675 675]
 [900 900 900 900]]


In [105]:
mask=mat2>
print(mask)

[45 45 45 45 45 45 45 45]


In [106]:
count = np.sum(mat2 > 500)
print(count)

8


Image Matrix Simulator (Very Important for AI)
🎯 Goal:Simulate grayscale image as NumPy array
image = np.random.randint(0, 256, (5,5))


Tasks:
Increase brightness (+50)
Clip values to 255
Find darkest pixel
Apply threshold (convert >128 to 255 else 0)
Flip image horizontally
Rotate 90 degrees

In [75]:
image=np.random.randint(0,255,(5,5))
print(image)

[[ 46 107 166   1 246]
 [ 34 198 208 189  78]
 [152 229 100  87 100]
 [247 199  98 167 117]
 [ 36 117 229 184  84]]


In [77]:
bright=image+50
print(bright)

[[ 96 157 216  51 296]
 [ 84 248 258 239 128]
 [202 279 150 137 150]
 [297 249 148 217 167]
 [ 86 167 279 234 134]]


In [78]:
bright_clipped = np.clip(bright, 0, 255)
print(bright_clipped)

[[ 96 157 216  51 255]
 [ 84 248 255 239 128]
 [202 255 150 137 150]
 [255 249 148 217 167]
 [ 86 167 255 234 134]]


In [82]:
darkest = np.min(image)
print(darkest)

1


In [86]:
thresholded = np.where(image > 128,255,0)
print(thresholded)

[[  0   0 255   0 255]
 [  0 255 255 255   0]
 [255 255   0   0   0]
 [255 255   0 255   0]
 [  0   0 255 255   0]]


In [87]:
flipped = np.fliplr(image)
print(flipped)

[[246   1 166 107  46]
 [ 78 189 208 198  34]
 [100  87 100 229 152]
 [117 167  98 199 247]
 [ 84 184 229 117  36]]


In [89]:
rotated = np.rot90(flipped)
print(rotated)

[[ 46  34 152 247  36]
 [107 198 229 199 117]
 [166 208 100  98 229]
 [  1 189  87 167 184]
 [246  78 100 117  84]]


Data Cleaning Simulator
data = np.array([10, 20, -5, 30, -2, 50, 1000])
Tasks:
Remove negative values
Replace outliers (>100) with mean
Standardize data (Z-score normalization)
Min-Max scaling

In [100]:
data = np.array([10, 20, -5, 30, -2, 50, 1000])
data=data[data>=0]
print(data)

[  10   20   30   50 1000]


In [98]:
mean=np.mean(data)
data[(data>100)]=mean
print(data)

[ 10  20  30  50 222]


In [101]:
std=np.std(data)
stand=(data-mean)/std
print(stand)

[-0.54467229 -0.5189802  -0.49328811 -0.44190393  1.99884452]


In [102]:
min=np.min(data)
max=np.max(data)
minmax=(data-min)/(max-min)
print(minmax)

[0.         0.01010101 0.02020202 0.04040404 1.        ]
